version: "3.8"
services:
  db:
    container_name: tsundoku-db
    image: mysql:8.0.30
    platform: linux/x86_64
    ports:
      - ${DB_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: ${DB_TIME_ZONE}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

volumes:
  mysql_data:
