server:
  port: ${env.APP_PORT}
  servlet:
    context-path: /api
    session:
      timeout: ${env.APP_SESSION_TIMEOUT}
spring:
  datasource:
    url: jdbc:mysql://${env.DB_HOST}:${env.DB_PORT}/${env.DB_NAME}
    username: ${env.DB_USER}
    password: ${env.DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
app:
  cors:
    allowed-origin: ${env.APP_CORS_ALLOWED_ORIGIN}
  cookie:
    same-site: ${env.APP_COOKIE_SAME_SITE}
